---
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    page-layout: full
    toc: false
editor_options: 
  chunk_output_type: console
---

# Course information

We will be working with [the NHANES dataset](https://functionaldataanalysis.org/dataset_nhanes.html) curated by the textbook, Functional Data Analysis with R.

# Schedule

+------+---------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| Week | Date                | Topic                                      | Reading                                                                                                                                                                                                                                                                                                                                                                          | Activity                                                    |
+======+=====================+============================================+:=================================================================================================================================================================================================================================================================================================================================================================================+=============================================================+
| 1    | 4/3 @4pm            | Intro                                      | -   [Best practices for analyzing large-scale health data from wearables and smartphone apps](https://ohsuitg-my.sharepoint.com/:b:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/S25_BSTA_500/Student_files/Readings/01_Best%20practices%20for%20analyzing%20large-scale%20health%20da.pdf?csf=1&web=1&e=T7PZVz)                                                         |                                                             |
+------+---------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| 2    | 4/11 @1pm (virtual) | Research Questions                         | -   [Functional Data Analysis with R, Section 1.2.1](https://ohsuitg-my.sharepoint.com/:b:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/S25_BSTA_500/Student_files/Readings/02_FDA_w_R_S1.2.1.pdf?csf=1&web=1&e=co7HmO)                                                                                                                                                  | -   Use R to explore NHANES data                            |
|      |                     |                                            |                                                                                                                                                                                                                                                                                                                                                                                  |                                                             |
|      |                     |                                            |                                                                                                                                                                                                                                                                                                                                                                                  | -   Reproduce Figure 1.1                                    |
+------+---------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| 3    | 4/17 @4pm           | Prepare Data                               | -   [acc: An R package to process, visualize, and analyze accelerometer data](https://ohsuitg-my.sharepoint.com/:b:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/S25_BSTA_500/Student_files/Readings/03_acc-%20An%20R%20package%20to%20process,%20visualize,%20and%20analyze%20accelerometer%20data.pdf?csf=1&web=1&e=TZeOcW)                                            | -   Use some of the functions in `acc` to explore your data |
+------+---------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| 4    | 4/23 @4pm           | Prepare Data: Missing data                 | -   [A framework for handling missing accelerometer outcome data in trials](https://ohsuitg-my.sharepoint.com/:b:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/S25_BSTA_500/Student_files/Readings/04_A%20framework%20for%20handling%20missing%20accelerometer%20out.pdf?csf=1&web=1&e=yGIUxv)                                                                           | -   TBD                                                     |
+------+---------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| 5    | 5/1 @4pm            | Analyze Data                               | -   [A Review of Statistical Analyses on Physical Activity Data Collected from Accelerometers](https://ohsuitg-my.sharepoint.com/:b:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/S25_BSTA_500/Student_files/Readings/05_A%20Review%20of%20Statistical%20Analyses%20on%20Physical%20Activ.pdf?csf=1&web=1&e=g0Ktk7)                                                      | -   TBD: maybe nothing, maybe performing a similar summary  |
+------+---------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| 6    | No class this week  | Analyze Data 1: Cross-sectional studies    | -   [The associations of physical activity patterns and the triglyceride-glucose index in US adults: a secondary data analysis of NHANES (2007–2018)](https://ohsuitg-my.sharepoint.com/:b:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/S25_BSTA_500/Student_files/Readings/06_The%20associations%20of%20physical%20activity%20patterns%20and.pdf?csf=1&web=1&e=upyX0X) |                                                             |
+------+---------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| 7    | 5/15 @4pm           | Analyze Data 2: Longitudinal Data Analysis | -   [Association of Longitudinal Activity Measures and Diabetes Risk: An Analysis From the National Institutes of Health All of Us Research Program](https://ohsuitg-my.sharepoint.com/:b:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/S25_BSTA_500/Student_files/Readings/07_Association%20of%20Longitudinal%20Activity%20Measures%20and%20.pdf?csf=1&web=1&e=WEdyn0)  |                                                             |
+------+---------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| 8    | 5/22 @4pm           | Analyze Data 3: Functional Data Analysis   | -   [Youtube Video on Intro to Functional Data Analysis (\~23 min)](https://www.youtube.com/watch?v=FjIK3YzUGG4&ab_channel=FunDataScience){.uri}                                                                                                                                                                                                                                 | -   Work through the R code for Section 4.0-4.1             |
|      |                     |                                            |                                                                                                                                                                                                                                                                                                                                                                                  |                                                             |
|      |                     |                                            | -   [Functional Data Analysis with R, Section 4.0-4.1](https://ohsuitg-my.sharepoint.com/:b:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/S25_BSTA_500/Student_files/Readings/08_FDA_w_R_S4.0-4.1.pdf?csf=1&web=1&e=xbQEzt)                                                                                                                                              |                                                             |
+------+---------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| 9    | 5/29 @4pm           | Analyze Data 3: Functional Data Analysis   | -   [Functional Data Analysis with R, Section 4.2-4.3](https://ohsuitg-my.sharepoint.com/:b:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/S25_BSTA_500/Student_files/Readings/09_FDA_w_R_S4.2-4.3.pdf?csf=1&web=1&e=5rLdBp)                                                                                                                                              | -   Work through the R code for Section 4.2-4.3             |
+------+---------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| 10   | 6/5 @4pm            | Share Results                              | -   TBD                                                                                                                                                                                                                                                                                                                                                                          |                                                             |
+------+---------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| 11   |                     |                                            |                                                                                                                                                                                                                                                                                                                                                                                  |                                                             |
+------+---------------------+--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+

: {.striped .hover tbl-colwidths="\[4, 6, 6, 20,20\]"}
